#!/usr/bin/env Rscript

sys = modules::import('klmr/sys')

sys$run({
    library(methods)
    input = commandArgs(trailingOnly = TRUE)
    tracks = do.call(c, lapply(input, rtracklayer::import.bedGraph))
    score = GenomicRanges::score
    sum_coverage = GenomicRanges::GRanges(GenomicRanges::coverage(tracks, weight = score(tracks)))
    # Numerical instability (?) causes some values to become negative.
    score(sum_coverage[score(sum_coverage) < 0]) = 0
    score(sum_coverage) = score(sum_coverage) / length(input)
    rtracklayer::export.bedGraph(sum_coverage, stdout())
})

# vim: ft=r
